title: <p align="center"> Rohan Bhale </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rohan-bhale-b6579b30/">LinkedIn</a> |
  <a href="https://github.com/rohanbhale12">GitHub</a>
  
  <br>   

  <br>
  </p>



theme: jekyll-theme-minimal
